
package au.net.electronichealth.ns.trd.tls.v2010;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransportResponseDeliveryService", targetNamespace = "http://ns.electronichealth.net.au/smd/svc/TransportResponseDelivery/2010", wsdlLocation = "smd-TransportResponseDelivery-TLS-2010.wsdl")
public class TransportResponseDeliveryService
    extends Service
{

    private final static URL TRANSPORTRESPONSEDELIVERYSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSPORTRESPONSEDELIVERYSERVICE_EXCEPTION;
    private final static QName TRANSPORTRESPONSEDELIVERYSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/smd/svc/TransportResponseDelivery/2010", "TransportResponseDeliveryService");

    static {
        TRANSPORTRESPONSEDELIVERYSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.trd.tls.v2010.TransportResponseDeliveryService.class.getResource("smd-TransportResponseDelivery-TLS-2010.wsdl");
        WebServiceException e = null;
        if (TRANSPORTRESPONSEDELIVERYSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'smd-TransportResponseDelivery-TLS-2010.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TRANSPORTRESPONSEDELIVERYSERVICE_EXCEPTION = e;
    }

    public TransportResponseDeliveryService() {
        super(__getWsdlLocation(), TRANSPORTRESPONSEDELIVERYSERVICE_QNAME);
    }

    public TransportResponseDeliveryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSPORTRESPONSEDELIVERYSERVICE_QNAME, features);
    }

    public TransportResponseDeliveryService(URL wsdlLocation) {
        super(wsdlLocation, TRANSPORTRESPONSEDELIVERYSERVICE_QNAME);
    }

    public TransportResponseDeliveryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSPORTRESPONSEDELIVERYSERVICE_QNAME, features);
    }

    public TransportResponseDeliveryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransportResponseDeliveryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransportResponseDelivery
     */
    @WebEndpoint(name = "TransportResponseDelivery")
    public TransportResponseDelivery getTransportResponseDelivery() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/smd/svc/TransportResponseDelivery/2010", "TransportResponseDelivery"), TransportResponseDelivery.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransportResponseDelivery
     */
    @WebEndpoint(name = "TransportResponseDelivery")
    public TransportResponseDelivery getTransportResponseDelivery(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/smd/svc/TransportResponseDelivery/2010", "TransportResponseDelivery"), TransportResponseDelivery.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSPORTRESPONSEDELIVERYSERVICE_EXCEPTION!= null) {
            throw TRANSPORTRESPONSEDELIVERYSERVICE_EXCEPTION;
        }
        return TRANSPORTRESPONSEDELIVERYSERVICE_WSDL_LOCATION;
    }

}
